/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ProizvodnjaRouteImport } from './routes/proizvodnja'
import { Route as PostaniPartnerRouteImport } from './routes/postani-partner'
import { Route as MediaKitRouteImport } from './routes/media-kit'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as JeansRouteImport } from './routes/jeans'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ChinoRouteImport } from './routes/chino'
import { Route as CargoRouteImport } from './routes/cargo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProizvodSlugRouteImport } from './routes/proizvod.$slug'
import { Route as AuthenticatedNarudzbaRouteImport } from './routes/_authenticated/narudzba'
import { Route as AuthenticatedCekanjeRouteImport } from './routes/_authenticated/cekanje'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiLineSheetSkuRouteImport } from './routes/api/line-sheet.$sku'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProizvodnjaRoute = ProizvodnjaRouteImport.update({
  id: '/proizvodnja',
  path: '/proizvodnja',
  getParentRoute: () => rootRouteImport,
} as any)
const PostaniPartnerRoute = PostaniPartnerRouteImport.update({
  id: '/postani-partner',
  path: '/postani-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaKitRoute = MediaKitRouteImport.update({
  id: '/media-kit',
  path: '/media-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const JeansRoute = JeansRouteImport.update({
  id: '/jeans',
  path: '/jeans',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinoRoute = ChinoRouteImport.update({
  id: '/chino',
  path: '/chino',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoRoute = CargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProizvodSlugRoute = ProizvodSlugRouteImport.update({
  id: '/proizvod/$slug',
  path: '/proizvod/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNarudzbaRoute = AuthenticatedNarudzbaRouteImport.update({
  id: '/narudzba',
  path: '/narudzba',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCekanjeRoute = AuthenticatedCekanjeRouteImport.update({
  id: '/cekanje',
  path: '/cekanje',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiLineSheetSkuRoute = ApiLineSheetSkuRouteImport.update({
  id: '/api/line-sheet/$sku',
  path: '/api/line-sheet/$sku',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cargo': typeof CargoRoute
  '/chino': typeof ChinoRoute
  '/faq': typeof FaqRoute
  '/jeans': typeof JeansRoute
  '/katalog': typeof KatalogRoute
  '/kontakt': typeof KontaktRoute
  '/media-kit': typeof MediaKitRoute
  '/postani-partner': typeof PostaniPartnerRoute
  '/proizvodnja': typeof ProizvodnjaRoute
  '/shop': typeof ShopRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cekanje': typeof AuthenticatedCekanjeRoute
  '/narudzba': typeof AuthenticatedNarudzbaRoute
  '/proizvod/$slug': typeof ProizvodSlugRoute
  '/api/line-sheet/$sku': typeof ApiLineSheetSkuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cargo': typeof CargoRoute
  '/chino': typeof ChinoRoute
  '/faq': typeof FaqRoute
  '/jeans': typeof JeansRoute
  '/katalog': typeof KatalogRoute
  '/kontakt': typeof KontaktRoute
  '/media-kit': typeof MediaKitRoute
  '/postani-partner': typeof PostaniPartnerRoute
  '/proizvodnja': typeof ProizvodnjaRoute
  '/shop': typeof ShopRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cekanje': typeof AuthenticatedCekanjeRoute
  '/narudzba': typeof AuthenticatedNarudzbaRoute
  '/proizvod/$slug': typeof ProizvodSlugRoute
  '/api/line-sheet/$sku': typeof ApiLineSheetSkuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cargo': typeof CargoRoute
  '/chino': typeof ChinoRoute
  '/faq': typeof FaqRoute
  '/jeans': typeof JeansRoute
  '/katalog': typeof KatalogRoute
  '/kontakt': typeof KontaktRoute
  '/media-kit': typeof MediaKitRoute
  '/postani-partner': typeof PostaniPartnerRoute
  '/proizvodnja': typeof ProizvodnjaRoute
  '/shop': typeof ShopRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/cekanje': typeof AuthenticatedCekanjeRoute
  '/_authenticated/narudzba': typeof AuthenticatedNarudzbaRoute
  '/proizvod/$slug': typeof ProizvodSlugRoute
  '/api/line-sheet/$sku': typeof ApiLineSheetSkuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cargo'
    | '/chino'
    | '/faq'
    | '/jeans'
    | '/katalog'
    | '/kontakt'
    | '/media-kit'
    | '/postani-partner'
    | '/proizvodnja'
    | '/shop'
    | '/admin'
    | '/cekanje'
    | '/narudzba'
    | '/proizvod/$slug'
    | '/api/line-sheet/$sku'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cargo'
    | '/chino'
    | '/faq'
    | '/jeans'
    | '/katalog'
    | '/kontakt'
    | '/media-kit'
    | '/postani-partner'
    | '/proizvodnja'
    | '/shop'
    | '/admin'
    | '/cekanje'
    | '/narudzba'
    | '/proizvod/$slug'
    | '/api/line-sheet/$sku'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cargo'
    | '/chino'
    | '/faq'
    | '/jeans'
    | '/katalog'
    | '/kontakt'
    | '/media-kit'
    | '/postani-partner'
    | '/proizvodnja'
    | '/shop'
    | '/_authenticated/admin'
    | '/_authenticated/cekanje'
    | '/_authenticated/narudzba'
    | '/proizvod/$slug'
    | '/api/line-sheet/$sku'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CargoRoute: typeof CargoRoute
  ChinoRoute: typeof ChinoRoute
  FaqRoute: typeof FaqRoute
  JeansRoute: typeof JeansRoute
  KatalogRoute: typeof KatalogRoute
  KontaktRoute: typeof KontaktRoute
  MediaKitRoute: typeof MediaKitRoute
  PostaniPartnerRoute: typeof PostaniPartnerRoute
  ProizvodnjaRoute: typeof ProizvodnjaRoute
  ShopRoute: typeof ShopRoute
  ProizvodSlugRoute: typeof ProizvodSlugRoute
  ApiLineSheetSkuRoute: typeof ApiLineSheetSkuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proizvodnja': {
      id: '/proizvodnja'
      path: '/proizvodnja'
      fullPath: '/proizvodnja'
      preLoaderRoute: typeof ProizvodnjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postani-partner': {
      id: '/postani-partner'
      path: '/postani-partner'
      fullPath: '/postani-partner'
      preLoaderRoute: typeof PostaniPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-kit': {
      id: '/media-kit'
      path: '/media-kit'
      fullPath: '/media-kit'
      preLoaderRoute: typeof MediaKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeans': {
      id: '/jeans'
      path: '/jeans'
      fullPath: '/jeans'
      preLoaderRoute: typeof JeansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chino': {
      id: '/chino'
      path: '/chino'
      fullPath: '/chino'
      preLoaderRoute: typeof ChinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargo': {
      id: '/cargo'
      path: '/cargo'
      fullPath: '/cargo'
      preLoaderRoute: typeof CargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proizvod/$slug': {
      id: '/proizvod/$slug'
      path: '/proizvod/$slug'
      fullPath: '/proizvod/$slug'
      preLoaderRoute: typeof ProizvodSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/narudzba': {
      id: '/_authenticated/narudzba'
      path: '/narudzba'
      fullPath: '/narudzba'
      preLoaderRoute: typeof AuthenticatedNarudzbaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cekanje': {
      id: '/_authenticated/cekanje'
      path: '/cekanje'
      fullPath: '/cekanje'
      preLoaderRoute: typeof AuthenticatedCekanjeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/line-sheet/$sku': {
      id: '/api/line-sheet/$sku'
      path: '/api/line-sheet/$sku'
      fullPath: '/api/line-sheet/$sku'
      preLoaderRoute: typeof ApiLineSheetSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCekanjeRoute: typeof AuthenticatedCekanjeRoute
  AuthenticatedNarudzbaRoute: typeof AuthenticatedNarudzbaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCekanjeRoute: AuthenticatedCekanjeRoute,
  AuthenticatedNarudzbaRoute: AuthenticatedNarudzbaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CargoRoute: CargoRoute,
  ChinoRoute: ChinoRoute,
  FaqRoute: FaqRoute,
  JeansRoute: JeansRoute,
  KatalogRoute: KatalogRoute,
  KontaktRoute: KontaktRoute,
  MediaKitRoute: MediaKitRoute,
  PostaniPartnerRoute: PostaniPartnerRoute,
  ProizvodnjaRoute: ProizvodnjaRoute,
  ShopRoute: ShopRoute,
  ProizvodSlugRoute: ProizvodSlugRoute,
  ApiLineSheetSkuRoute: ApiLineSheetSkuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
